version: '3.8'

services:
  postgres-test:
    image: postgres:15-alpine
    container_name: lumir-evaluation-postgres-test
    restart: no
    environment:
      POSTGRES_DB: lumir_evaluation_test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5434:5432'
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    networks:
      - lumir-evaluation-test-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U test_user -d lumir_evaluation_test']
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  postgres_test_data:
    driver: local

networks:
  lumir-evaluation-test-network:
    driver: bridge
